name: Check

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "cmake/**"
      - "test/**"
      - "upgrade_test/**"
      - "*.md"
      - "*.sql"

# Concurrency control to cancel previous runs on new push to same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true  # Automatically cancel any previous runs for the same group

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: use clang-format 13
        run: pip3 install clang-format==13.0.1
      - name: Check clang code style
        run: git ls-files *.{c,h} | xargs clang-format -i --style=file && git diff --exit-code

  build_and_test:
    needs: lint
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        version: [ggdb6, ggdb7]
    container:
      image: ghcr.io/greengagedb/greengage/${{ matrix.version }}_ubuntu:latest
      options:
        --sysctl "kernel.sem=500 1024000 200 4096"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build and install
        shell: bash
        run: bash $GITHUB_WORKSPACE/ci/install.bash
        working-directory: /home/gpadmin
      - name: Tests
        run: su gpadmin -c 'bash ci/test.bash'
      - name: Collect logs
        if: always()
        shell: bash
        run: |
          params=(
            "./ d gpAdminLogs"
            "gpdb_src/gpAux/gpdemo/datadirs/ d log"
            "gpdb_src/gpAux/gpdemo/datadirs/ d pg_log"
          )
          for param in "${params[@]}"; do
            read -r path type name <<< "$param"
            find $path -name $name -type $type -exec tar -rf "/logs/$name.tar" {} \;
          done
        working-directory: /home/gpadmin
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diskquota_${{ matrix.version }}_ubuntu_logs
          path: /logs/*
